T="$HERE/../core/specify/templates"
assert_file "$T/prd-template.md"        "prd template exists"
assert_file "$T/spec-template.md"       "spec template exists"
assert_file "$T/plan-template.md"       "plan template exists"
assert_file "$T/tasks-template.md"      "tasks template exists"
assert_file "$T/checklist-template.md"  "checklist template exists"
assert_contains "$T/spec-template.md" "status: draft" "spec template has status frontmatter"
assert_contains "$T/plan-template.md" "status: draft" "plan template has status frontmatter"
assert_contains "$T/plan-template.md" "Data Layer Contract" "plan template has data-layer contract section"
assert_contains "$T/prd-template.md" "Dependencies & Interfaces" "prd template has dependencies/interfaces section"
assert_contains "$T/prd-template.md" "Consumes (inputs)" "prd template asks what the feature consumes"
assert_contains "$T/prd-template.md" "Exposes (outputs)"     "prd template asks what the feature exposes"
assert_file "$HERE/../core/specify/memory/constitution.md.tmpl" "constitution template exists"
assert_file "$HERE/../core/specify/memory/product.md.tmpl" "product brief template exists"
assert_contains "$HERE/../core/specify/memory/product.md.tmpl" "North-star Metric" "product template has north-star section"
assert_contains "$HERE/../core/specify/memory/product.md.tmpl" "Non-goals" "product template has non-goals section"
