T="$HERE/../core/specify/templates"
assert_file "$T/prd-template.md"        "prd template exists"
assert_file "$T/spec-template.md"       "spec template exists"
assert_file "$T/plan-template.md"       "plan template exists"
assert_file "$T/tasks-template.md"      "tasks template exists"
assert_file "$T/checklist-template.md"  "checklist template exists"
assert_contains "$T/spec-template.md" "status: draft" "spec template has status frontmatter"
assert_contains "$T/plan-template.md" "status: draft" "plan template has status frontmatter"
assert_contains "$T/plan-template.md" "Contrato da Camada de Dados" "plan template has data-layer contract section"
assert_contains "$T/prd-template.md" "Dependências e Interfaces" "prd template has dependencies/interfaces section"
assert_contains "$T/prd-template.md" "Consome (entradas)" "prd template asks what the feature consumes"
assert_contains "$T/prd-template.md" "Expõe (saídas)"     "prd template asks what the feature exposes"
assert_file "$HERE/../core/specify/memory/constitution.md.tmpl" "constitution template exists"
